turbolinks_verification-main/config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'example' => 'example#index'
end

turbolinks_verification-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

turbolinks_verification-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

turbolinks_verification-main/app/controllers/example_controller.rb
class ExampleController < ApplicationController
end

turbolinks_verification-main/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

turbolinks_verification-main/app/helpers/application_helper.rb
module ApplicationHelper
end

turbolinks_verification-main/app/helpers/example_helper.rb
module ExampleHelper
end

turbolinks_verification-main/app/helpers/homes_helper.rb
module HomesHelper
end

turbolinks_verification-main/app/views/example/index.html.erb
Turbolinksの検証

turbolinks_verification-main/app/views/homes/top.html.erb
<h1>トップページ</h1>
<%= link_to "別ページへ", example_path %>

turbolinks_verification-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurbolinksSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>